openapi: 3.1.2
info: 
  title: Abonneer op gebeurtenis type van persoon command definitie
  version: 1.0.0
components: 
  schemas:
    AbonneerOpGebeurtenisTypeVanPersoonCommand:
      allOf: 
        - $ref: './abonneer-command-v1.yaml#/components/schemas/AbonneerCommand'
        - type: object
          properties:
            gebeurtenisType:
              $ref: 'gebeurtenis-type-van-persoon-enum-v1.yaml#/components/schemas/GebeurtenisTypeVanPersoonEnum'
              description: Het gebeurtenistype waarop de abonnee zich wil abonneren
            burgerservicenummer:
              $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
              description: Het burgerservicenummer (BSN) van de persoon waarvoor de abonnee gebeurtenissen van het opgegeven type wil ontvangen
          required:
            - gebeurtenisType
            - burgerservicenummer
