openapi: 3.1.2
info: 
  title: Abonnee type definitie
  version: 1.0.0
components:
  schemas:
    Abonnee:
      type: object
      properties:
        naam:
          $ref: './naam-v1.yaml#/components/schemas/AbonneeNaam'
          description: De naam van de abonnee, uniek voor een afnemer