openapi: 3.1.2
info: 
  title: Gebeurtenistype path parameter definitie
  version: 1.0.0
components:
  parameters:
    GebeurtenistypePathParameter:
      name: gebeurtenistype
      in: path
      required: true
      schema:
        $ref: './gebeurtenis-type-van-persoon-enum-v1.yaml#/components/schemas/GebeurtenisTypeVanPersoonEnum'
