openapi: 3.1.2
info: 
  title: Groep naam path parameter definitie
  version: 1.0.0
components:
  parameters:
    GroepNaamPathParameter:
      name: groepNaam
      in: path
      required: true
      schema:
        $ref: './naam-v1.yaml#/components/schemas/GroepNaam'
        description: De naam van de abonnee
