openapi: 3.1.2
info: 
  title: Zeg op abonnement op gebeurtenis type van persoon command definitie
  version: 1.0.0
components: 
  schemas:
    ZegOpAbonnementOpGebeurtenisTypeVanPersoonCommand:
      allOf: 
        - $ref: './abonnementen-command-v1.yaml#/components/schemas/AbonnementenCommand'
        - type: object
          description: Beëindigen van een 'gebeurtenis type van persoon' abonnement van een abonnee.
          properties:
            gebeurtenisType:
              $ref: 'gebeurtenis-type-van-persoon-enum-v1.yaml#/components/schemas/GebeurtenisTypeVanPersoonEnum'
            burgerservicenummer:
              $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
          required:
            - gebeurtenisType
            - burgerservicenummer
