openapi: 3.1.0
info:
  title: Verblijfplaats data (binnenlands)
  description: |
    Verblijfplaats
  version: 1.0.0
components:
  schemas:
    verblijfplaatsBinnenland:
      allOf:
        - $ref: "verblijfplaats-basis.yaml#/components/schemas/c08"
        - type: object
          properties:
            e1030:
              $ref: datum-aanvang-adreshouding.yaml