openapi: 3.1.0
info:
  title: Classificatie Event
  version: 1.0.0
  description: Minimale specificatie op basis van de CloudEvent specificatie met alleen de velden 'type' en 'data'.
components:
  schemas:
    Event:
      type: object
      required:
        - type
        - data
      discriminator:
        propertyName: type
        mapping:
          nl.brp.ingeschreven.geboorte: "ingeschreven-event.yaml#/components/schemas/IngeschrevenGeboorteEvent"
          nl.brp.ingeschreven.immigratie: "ingeschreven-event.yaml#/components/schemas/IngeschrevenImmigratieEvent"
          nl.brp.ingeschreven.niet-ingezetene: "ingeschreven-event.yaml#/components/schemas/IngeschrevenNietIngezeteneEvent"
          nl.brp.verhuisd.binnengemeentelijk: "verhuisd-event.yaml#/components/schemas/VerhuisdBinnengemeentelijkEvent"
          nl.brp.verhuisd.buitengemeentelijk: "verhuisd-event.yaml#/components/schemas/VerhuisdBuitengemeentelijkEvent"
          nl.brp.verhuisd.emigratie: "verhuisd-event.yaml#/components/schemas/VerhuisdEmigratieEvent"
          nl.brp.verhuisd.immigratie: "verhuisd-event.yaml#/components/schemas/VerhuisdImmigratieEvent"
          nl.brp.verhuisd.in-buitenland: "verhuisd-event.yaml#/components/schemas/VerhuisdInBuitenlandEvent"
      properties:
        type:
          type: string
          description: Het type van het event
        data:
          type: object
          description: Event-specifieke data
