openapi: 3.1.0
info:
  title: Persoon Ingeschreven Event
  version: 1.0.0
components:
  schemas:
    IngeschrevenEvent:
      oneOf:
        - $ref: "#/components/schemas/IngeschrevenGeboorte"
        - $ref: "#/components/schemas/IngeschrevenNietIngezeten"
        - $ref: "#/components/schemas/IngeschrevenImmigratie"
    IngeschrevenGeboorte:
      allOf:
        - $ref: ../cloud-events/cloud-events-v1.0.2.json
        - required:
            - type
            - data
        - type: object
          properties:
            type:
              enum: [nl.brp.ingeschreven.geboorte]
            data:
              type: object
              required:
                - pl_id
              properties:
                pl_id:
                  $ref: ../ids/pl-id.yaml#/components/schemas/PlId
    IngeschrevenNietIngezeten:
      allOf:
        - $ref: ../cloud-events/cloud-events-v1.0.2.json
        - required:
            - type
            - data
        - type: object
          properties:
            type:
              enum: [nl.brp.ingeschreven.niet-ingezeten]
            data:
              type: object
              required:
                - pl_id
              properties:
                pl_id:
                  $ref: ../ids/pl-id.yaml#/components/schemas/PlId
    IngeschrevenImmigratie:
      allOf:
        - $ref: ../cloud-events/cloud-events-v1.0.2.json
        - required:
            - type
            - data
        - type: object
          properties:
            type:
              enum: [nl.brp.ingeschreven.immigratie]
            data:
              type: object
              required:
                - pl_id
              properties:
                pl_id:
                  $ref: ../ids/pl-id.yaml#/components/schemas/PlId
