openapi: 3.1.0
info:
  title: Persoon Ingeschreven Event
  version: 1.0.0
components:
  schemas:
    IngeschrevenGeboorteEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          required:
            - "data"
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenData"
      example:
        type: nl.brp.ingeschreven.geboorte
        data:
          pl_id: "123456789"
    IngeschrevenImmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          required:
            - "data"
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenData"
          example:
            type: nl.brp.ingeschreven.immigratie
            data:
              pl_id: "123456789"
    IngeschrevenNietIngezeteneEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          required:
            - "data"
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenData"
          example:
            type: nl.brp.ingeschreven.niet-ingezetene
            data:
              pl_id: "123456789"
    IngeschrevenData:
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"