openapi: 3.1.0
info:
  title: Persoon Ingeschreven Event
  version: 1.0.0
components:
  schemas:
    IngeschrevenEvent:
      oneOf:
        - $ref: "#/components/schemas/IngeschrevenGeboorteEvent"
        - $ref: "#/components/schemas/IngeschrevenImmigratieEvent"
        - $ref: "#/components/schemas/IngeschrevenNietIngezetenEvent"
      discriminator:
        propertyName: type
        mapping:
          nl.brp.ingeschreven.geboorte: "#/components/schemas/IngeschrevenGeboorteEvent"
          nl.brp.ingeschreven.immigratie: "#/components/schemas/IngeschrevenImmigratieEvent"
          nl.brp.ingeschreven.niet-ingezeten: "#/components/schemas/IngeschrevenNietIngezetenEvent"
    IngeschrevenGeboorteEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenGeboorteData"
      example:
        type: nl.brp.ingeschreven.geboorte
        data:
          pl_id: "123456789"
    IngeschrevenGeboorteData:
      type: object
      properties:
        pl_id:
          type: string
    IngeschrevenImmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenImmigratieData"
      example:
        type: nl.brp.ingeschreven.immigratie
        data:
          pl_id: "123456789"
    IngeschrevenImmigratieData:
      type: object
      properties:
        pl_id:
          type: string
    IngeschrevenNietIngezetenEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/IngeschrevenNietIngezetenData"
      example:
        type: nl.brp.ingeschreven.niet-ingezeten
        data:
          pl_id: "123456789"
    IngeschrevenNietIngezetenData:
      type: object
      properties:
        pl_id:
          type: string
