openapi: 3.1.0
info: 
  title: Persoon Ingeschreven Event
  version: 1.0.0
components: 
  schemas:
    IngeschrevenOpAdresEvent:
      allOf: 
        - $ref: ../cloud-events/cloud-events-v1.0.2.json
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/IngeschrevenOpAdres'
    IngeschrevenOpAdres:
      type: object
      properties:
          pl_id:
            $ref: '../ids/pl-id.yaml#/components/schemas/PlId'
          adres_id:
            $ref: '../ids/adres-id.yaml#/components/schemas/AdresId'
        


  