openapi: 3.1.0
info:
  title: Persoon Ingeschreven Event
  version: 1.0.0
components:
  schemas:
    VerhuisdBinnengemeentelijkEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdBinnengemeentelijkData"
      example:
        type: nl.brp.verhuisd.binnengemeentelijk
        data:
          pl_id: "123456789"
          adres_id: "1122334455"
    VerhuisdBinnengemeentelijkData:
      type: object
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"
        adres_id:
          $ref: "../ids/adres-id.yaml#/components/schemas/AdresId"
    VerhuisdBuitengemeentelijkEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdBuitengemeentelijkData"
      example:
        type: nl.brp.verhuisd.buitengemeentelijk
        data:
          pl_id: "123456789"
          adres_id: "1122334455"
    VerhuisdBuitengemeentelijkData:
      type: object
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"
        adres_id: 
          $ref: "../ids/adres-id.yaml#/components/schemas/AdresId"
    VerhuisdEmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdEmigratieData"
      example:
        type: nl.brp.verhuisd.emigratie
        data:
          pl_id: "123456789"
          adres_id: "1122334455"
    VerhuisdEmigratieData:
      type: object
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"
    VerhuisdImmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdImmigratieData"
      example:
        type: nl.brp.verhuisd.emigratie
        data:
          pl_id: "123456789"
          adres_id: "1122334455"
    VerhuisdImmigratieData:
      type: object
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"
        adres_id:
          $ref: "../ids/adres-id.yaml#/components/schemas/AdresId"
    VerhuisdBuitenlandsEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/Event"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdBuitenlandsData"
      example:
        type: nl.brp.verhuisd.buitenlands
        data:
          pl_id: "123456789"
          adres_id: "1122334455"
    VerhuisdBuitenlandsData:
      type: object
      properties:
        pl_id:
          $ref: "../ids/pl-id.yaml#/components/schemas/PlId"
