openapi: 3.1.0
info:
  title: Persoon Ingeschreven Event
  version: 1.0.0
components:
  schemas:
    VerhuisdEvent:
      oneOf:
        - $ref: "#/components/schemas/VerhuisdGeboorteEvent"
        - $ref: "#/components/schemas/VerhuisdImmigratieEvent"
        - $ref: "#/components/schemas/VerhuisdEmigratieEvent"
        - $ref: "#/components/schemas/VerhuisdBuitenlandsEvent"
      discriminator:
        propertyName: type
        mapping:
          nl.brp.verhuisd.geboorte: "#/components/schemas/VerhuisdGeboorteEvent"
          nl.brp.verhuisd.immigratie: "#/components/schemas/VerhuisdImmigratieEvent"
          nl.brp.verhuisd.emigratie: "#/components/schemas/VerhuisdEmigratieEvent"
          nl.brp.verhuisd.buitenlands: "#/components/schemas/VerhuisdBuitenlandsEvent"
    VerhuisdGeboorteEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdGeboorteData"
      example:
        type: nl.brp.verhuisd.geboorte
        data:
          pl_id: "123456789"
    VerhuisdGeboorteData:
      type: object
      properties:
        pl_id:
          type: string
    VerhuisdImmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdImmigratieData"
      example:
        type: nl.brp.verhuisd.immigratie
        data:
          pl_id: "123456789"
    VerhuisdImmigratieData:
      type: object
      properties:
        pl_id:
          type: string
    VerhuisdEmigratieEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdEmigratieData"
      example:
        type: nl.brp.verhuisd.emigratie
        data:
          pl_id: "123456789"
    VerhuisdEmigratieData:
      type: object
      properties:
        pl_id:
          type: string
    VerhuisdBuitenlandsEvent:
      allOf:
        - $ref: "classificatie-event.yaml#/components/schemas/ClassificatieEvent"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/VerhuisdBuitenlandsData"
      example:
        type: nl.brp.verhuisd.buitenlands
        data:
          pl_id: "123456789"
    VerhuisdBuitenlandsData:
      type: object
      properties:
        pl_id:
          type: string
