openapi: 3.1.0
info:
  title: Adres Id
  description: |
    Definitie voor Adres id, een unieke identifier van een adres
  version: 1.0.0
components:
  schemas:
    AdresId:
      type: string
      example: "1122334455"
