openapi: 3.1.0
info:
  title: PL Id
  description: |
    Definitie voor PL id, een unieke identifier van een persoonslijst
  version: 1.0.0
components:
  schemas:
    PlId:
      type: string
      example: "123456789"