replicaCount: 1

image:
  repository: ghcr.io/brp-api/brp-api-gebeurtenissen
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8888
  targetPort: 8888

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  initialDelaySeconds: 40
  periodSeconds: 3
  timeoutSeconds: 3
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  initialDelaySeconds: 30
  periodSeconds: 3
  timeoutSeconds: 3
  failureThreshold: 3

env:
  AXON_AXONSERVER_SERVERS: "axon"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://brpv-db:5432/rvig_haalcentraal_testdata"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  PROJECTIONS_DATASOURCE_URL: "jdbc:postgresql://projecties-db:5432/rvig_brpapi_projecties"
  PROJECTIONS_DATASOURCE_USERNAME: "root"
  PROJECTIONS_DATASOURCE_PASSWORD: "root"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI: "http://keycloak:8080/realms/brp-api"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: "http://keycloak:8080/realms/brp-api/protocol/openid-connect/certs"
