openapi: 3.1.2
info: 
  title: paginering
  version: 1.0.0
components:
  schemas:
    Cursor:
      description: Unieke gebeurtenis-id als cursor voor paginering.
      type: string
      example: "123e4567-e89b-12d3-a456-426614174000"
    Limiet:
      description: Aantal te retourneren gebeurtenissen
      type: integer
      minimum: 1
      maximum: 10
      example: 3