openapi: 3.1.0
info:
  title: BRP API gebeurtenissen specificatie
  version: 1.0.0
components: 
  schemas:
    Gebeurtenis:
      oneOf:
        - $ref: './verhuisd-intergemeentelijk-v1.yaml#/components/schemas/VerhuisdIntergemeentelijk'
      discriminator: 
        propertyName: type
        mapping:
          nl.brp.verhuisd.intergemeentelijk: 'verhuisd-intergemeentelijk-v1.yaml#/components/schemas/VerhuisdIntergemeentelijk'