openapi: 3.1.2
info: 
  title: verhuisd naar buitenland gebeurtenis specificatie
  version: 1.0.0
components:
  schemas:
    VerhuisdNaarBuitenland:
      allOf: 
        - $ref: gebeurtenis-v1.yaml#/components/schemas/Gebeurtenis
        - type: object
          required: 
            - data
          properties:
            data:
              $ref: '#/components/schemas/VerhuisdNaarBuitenlandData'

    VerhuisdNaarBuitenlandData:
      type: object
      properties:
        burgerservicenummer:
              $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        verblijfplaats:
          $ref: '../verblijfplaats/verblijfplaats-buitenland-v1.yaml#/components/schemas/VerblijfplaatsBuitenland'
