openapi: 3.1.0
info: 
  title: verhuisd intergemeentelijk gebeurtenis specificatie
  version: 1.0.0
components:
  schemas:
    VerhuisdIntergemeentelijk:
      allOf: 
        - $ref: 'gebeurtenis-v1.yaml#/components/schemas/Gebeurtenis'
        - type: object
          required: 
            - data
          properties:
            data:
              $ref: '#/components/schemas/VerhuisdIntergemeentelijkData'

    VerhuisdIntergemeentelijkData:
      type: object
      properties:
        burgerservicenummer:
              $ref: '../../brp/identificatienummers/burgerservicenummer-v1.yaml#/components/schemas/Burgerservicenummer'
        verblijfplaats:
          $ref: '../verblijfplaats/verblijfplaats-binnenland-v1.yaml#/components/schemas/VerblijfplaatsBinnenland'