openapi: 3.1.2
info: 
  title: datum
  version: 1.0.0
components:
  schemas:
    Datum:
      type: string
      pattern: ^(18|19|20|21|22)[0-9]{2}((0[1-9]|1[0-2])((0[1-9]|[12][0-9]|3[01])|00)|0000)|00000000$
