openapi: 3.1.0
info:
  title: CloudEvents Specification YAML Format
  version: 1.0.2
components: 
  schemas:
    CloudEvent:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/typedef'
        data:
          $ref: '#/components/schemas/datadef'
        id:
          $ref: '#/components/schemas/iddef'
        source:
          $ref: "#/components/schemas/sourcedef"
        specversion:
          $ref: '#/components/schemas/specversiondef'

    typedef:
      description: |
        Describes the type of event related to the originating occurrence.
      type: string
      minLength: 1

    datadef:
      description: |
        The event payload.
      type: object
      
    iddef:
      description: |
        Identifies the event.
      type: string
      minLength: 1
    
    sourcedef:
      description: |
        Identifies the context in which an event happened.
      type: string
      format: uri-reference
      minLength: 1
      example: urn:uuid:0f0c73ae-d9c6-48a4-b935-ecd114564ae0

    specversiondef:
      description: |
        The version of the CloudEvents specification which the event uses. 
        This enables the interpretation of the context. 
        Compliant event producers MUST use a value of 1.0 when referring to this version of the specification.
      type: string
      minLength: 1
      example: '1.0'
    
    

