openapi: 3.1.0
info:
  title: CloudEvents Specification YAML Format
  version: 1.0.2
components: 
  schemas:
    CloudEvent:
      type: object
      properties:
        id:
          description: "Identifies the event."
          $ref: '#/components/schemas/iddef'
        source:
          description: "Identifies the context in which an event happened."
          $ref: '#/components/schemas/sourcedef'
        specversion:
          description: "The version of the CloudEvents specification which the event uses."
          $ref: '#/components/schemas/specversiondef'
        type:
          description: "Describes the type of event related to the originating occurrence."
          $ref: '#/components/schemas/typedef'
        data:
          description: "The event payload."
          $ref: '#/components/schemas/datadef'
      required:
        - id
        - source
        - specversion
        - type

    typedef:
      type: string
      minLength: 1

    datadef:
      type: object

    iddef:
      type: string
      format: uuid

    sourcedef:
      type: string
      format: uri-reference
      minLength: 1
    
    specversiondef:
      type: string
      minLength: 1
