services:
  proxy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

    networks:
      - brp-api-network

volumes:
  caddy_data:
  caddy_config:

networks:
  brp-api-network:
    name: brp-api-network
