services:
  abonneer-service:
    image: ghcr.io/brp-api/gebeurtenis-abonnementen-service:latest
    container_name: abonneer-service
    depends_on:
      - keycloak
      - axonserver
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver:8124
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/brp-api
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak:8080/realms/brp-api/protocol/openid-connect/certs
    ports:
      - "8003:8094"
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network