services:
  mutatie-service:
    image: ghcr.io/brp-api/gebeurtenis-mutatie-service:latest
    container_name: mutatie-service
    ports:
      - "8000:8000"
    environment:
      - GEBEURTENIS_URL=http://gebeurtenissen:8888/personen/gebeurtenissen
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rvig_haalcentraal_testdata
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network