services:
  bevraag-service:
    image: ghcr.io/brp-api/gebeurtenis-bevragen-service:latest
    container_name: bevraag-service
    depends_on:
      - axonserver
      - postgres
    ports:
      - "8002:8082"
    environment:
      - AXON_AXONSERVER_SERVERS=axonserver:8124
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://keycloak:8080/realms/brp-api
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://keycloak:8080/realms/brp-api/protocol/openid-connect/certs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rvig_haalcentraal_testdata
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
