services:
  mutatie-service:
    image: ghcr.io/brp-api/gebeurtenis-mutatie-service:latest
    container_name: mutatie-service
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      - GEBEURTENIS-PUBLICEREN_BASE-URL=http://publiceer-service:8080/personen/gebeurtenissen
      - GEBEURTENIS-PUBLICEREN_AUTH=Bearer some-token-value
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rvig_haalcentraal_testdata
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
