apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gebeurtenissen-mutatie-service.fullname" . }}
  labels:
    {{- include "gebeurtenissen-mutatie-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gebeurtenissen-mutatie-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gebeurtenissen-mutatie-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "gebeurtenissen-mutatie-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
