openapi: 3.1.0
info:
  title: adresseerbaar object identificatie specificatie
  version: 1.0.0
components:
  schemas:
    AdresseerbaarObjectIdentificatie:
      type: string
      title: Identificatiecode verblijfplaats
      description: |
        De identificatiecode van een adresseerbaar object.
      pattern: ^[0-9]{16}$

    AdresseerbaarObjectIdentificatieAdres:
      type: object
      description: |
        Adres groep met adresseerbaar object identificatie veld.
      properties:
        e1180:
          $ref: '#/components/schemas/AdresseerbaarObjectIdentificatie'
