openapi: 3.1.2
info: 
  title: overleden gebeurtenis specificatie
  version: 1.0.0
components:
  schemas:
    Overleden:
      allOf: 
        - $ref: 'gebeurtenis-v1.yaml#/components/schemas/Gebeurtenis'
        - type: object
          required: 
            - data
          properties:
            data:
              $ref: '#/components/schemas/OverledenData'

    OverledenData:
      type: object
      properties:
        c01:
          $ref: '../identificatienummers/anummer-v1.yaml#/components/schemas/AnummerIdentificatieNummers'
        c06:
          $ref: '#/components/schemas/OverlijdenData'
      required: 
        - c01
        - c06

    OverlijdenData:
      type: object
      properties:
        e0810:
          $ref: '../datum-v1.yaml#/components/schemas/Datum'
          description: Datum overlijden
      required: 
        - e0810
