openapi: 3.1.2
info: 
  title: verhuisd naar buitenland gebeurtenis specificatie
  version: 1.0.0
components:
  schemas:
    VerhuisdNaarBuitenland:
      allOf: 
        - $ref: 'gebeurtenis-v1.yaml#/components/schemas/Gebeurtenis'
        - type: object
          required: 
            - data
          properties:
            data:
              $ref: '#/components/schemas/VerhuisdNaarBuitenlandData'

    VerhuisdNaarBuitenlandData:
      type: object
      properties:
        c01:
          $ref: '../identificatienummers/anummer-v1.yaml#/components/schemas/AnummerIdentificatieNummers'
        c08:
          $ref: '#/components/schemas/AdresBuitenlandData'
      required: 
        - c01
        - c08

    AdresBuitenlandData:
      type: object
      properties:
        e1320:
          $ref: '../datum-v1.yaml#/components/schemas/Datum'
          description: Datum aanvang adres buitenland
      required:
        - e1320
